version: "3.8"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    ports:
      - "8000:8000"